version: '3.4'

services:
  mediporta-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: src/Mediporta.Api
      dockerfile: Dockerfile
    ports:
     - "7219:80"
    depends_on:
     - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    ports:
      - '1433:1433'
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
